<main>

    <?php require "templates/partials/speed.php" ?>

    <form id="searchForm" method="get" action="index_fin.php">
        <fieldset>
            <label for="choix_2">Quel chemin choisissez-vous?</label><br>
            <select name="choix_2">
                <option value="right_path">chemin de droite</option>
                <option value="left_path">chemin de gauche</option>
            </select>
        <fieldset>
        <fieldset>
            <button type="submit">Lancer la recherche</button>
        </fieldset>
    </form>
</main>