<?php
//Tableau qui décrit les différentes possibilités d'histoire du jeu après que l'utilisateur ait choisi la vitesse qu'il veut prendre pour le 10km
$courses = [
    [
        "type_course" => "speed",
        "histoire" => "
                        <p>
                            Vous avez choisi de courrir vite pour atteindre votre objectif. 
                            Au cinquième kilomètre vous êtes donc déjà essouflés et les jambes sont lourdes.<br> 
                            Pour faire les 5 derniers kilomètres vous devez choisir entre:
                        </p>
                        
                        <ul>
                            <li>Le chemin à droite qui est un chemin très valloné sur tout le reste de la course.</li>
                            <li>Le chemin de gauche qui est un chemin de pierres instables sur tout le reste de la course.</li>
                        </ul>"
    ],
    [
        "type_course" => "fundamental_endurance",
        "histoire" => " 
                        <p>
                            Vous avez choisi de courrir en endurance fondamentale pour atteindre votre objectif. 
                            Au cinquième kilomètre vous êtes donc encore en forme mais les jambes commencent à être lourdes.<br>  
                            Pour faire les 5 derniers kilomètres vous devez choisir entre:
                        </p> 

                        <ul>
                            <li>Le chemin à droite qui est un chemin très valloné sur tout le reste de la course.</li>
                            <li>Le chemin de gauche qui est un chemin de pierres instables sur tout le reste de la course.</li>
                        </ul>"
    ],
    [
        "type_course" => "slow",
        "histoire" => "
                        <p>
                            Vous avez choisi de courrir lentement pour atteindre votre objectif. 
                            Au cinquième kilomètre vous êtes donc encore en forme et les jambes sont fraîches.<br>  
                            Pour faire les 5 derniers kilomètres vous devez choisir entre:
                        </p>

                        <ul>
                            <li>Le chemin à droite qui est un chemin très valloné sur tout le reste de la course.</li>
                            <li>Le chemin de gauche qui est un chemin de pierres instables sur tout le reste de la course.</li>
                        </ul>"
    ]
];

//fonction session qui permet de garder en mémoire des données pour les réutiliser plus tard sur d'autres pages. Start signifie qu'on lance la session
session_start();
//On enregistre dans la session la valeur récupérée par get pour l'utiliser dans le fichier path.php plus tard
$_SESSION["choix_1"] = $_GET["choix_1"]; 
$choix_1 = $_GET["choix_1"];

//On parcourt le tableau $courses et on affiche le contenu $course["histoire"] seulement si le contenu $course["type_course"] correspond au $choix_1
foreach ($courses as $course) {
    if ($course["type_course"] === $choix_1) {
        echo $course["histoire"];
    }
}

?>
<!--Formulaire pour réaliser la deuxième étape du jeu-->
<form id="searchForm" method="get" action="index.php">
    <fieldset>
        <input type="hidden" name="page" value="etape_2"> <!--valeur qui sera récupérée avec un get et utilisée pour pouvoir afficher uniquement la page nécessaire dans l'index-->
        <label for="choix_2">Quel chemin choisissez-vous?</label><br>
        <select name="choix_2">
            <option value="right_path">chemin de droite</option>
            <option value="left_path">chemin de gauche</option>
        </select>
    </fieldset>
    <fieldset>
        <button type="submit">Lancer la recherche</button>
    </fieldset>
</form>

